# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0002_auto_20191118_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_tag',
            field=models.CharField(default='willChange', max_length=20),
            preserve_default=False,
        ),
    ]
