# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0004_settings_standings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standings',
            old_name='loses',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='standings',
            name='ties',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
