# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0005_auto_20191119_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='ability',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
