# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0006_auto_20191119_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='pts_against',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standings',
            name='pts_for',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
