# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0007_auto_20191120_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='myTeam',
            field=models.IntegerField(),
        ),
    ]
