# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0008_auto_20191120_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standings',
            old_name='pts_against',
            new_name='pts_against_avg',
        ),
        migrations.RenameField(
            model_name='standings',
            old_name='pts_for',
            new_name='pts_for_avg',
        ),
    ]
