# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0009_auto_20191121_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='pts_against_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='standings',
            name='pts_for_avg',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
