# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0011_auto_20191121_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicalStandings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('win_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pts_for', models.IntegerField()),
                ('pts_against', models.IntegerField()),
                ('champ_wins', models.IntegerField()),
                ('champ_losses', models.IntegerField()),
                ('champ_win_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
